In [53]:
import numpy as np

In [54]:
random_matrix_A = np.random.rand(10,10)
print("Random 10x10 Matrix A:")
print(random_matrix_A)

Random 10x10 Matrix A:
[[0.98111619 0.03225002 0.91296644 0.97376788 0.93677371 0.91818533
  0.86098802 0.46772554 0.13465316 0.06316144]
 [0.38120008 0.26045228 0.091819   0.24193422 0.69584936 0.35390193
  0.49763686 0.96113741 0.47011719 0.59901144]
 [0.08977827 0.18303875 0.73922453 0.91879013 0.00157749 0.12530819
  0.98370455 0.79173365 0.72262677 0.4725534 ]
 [0.50065542 0.93990639 0.08776578 0.06008322 0.37766752 0.78335248
  0.64605652 0.01586882 0.7988971  0.08789932]
 [0.28556066 0.22715969 0.03573578 0.79975483 0.34001278 0.09409613
  0.98072596 0.00785681 0.74920926 0.66824758]
 [0.09279125 0.99184708 0.08846934 0.76512672 0.66116573 0.21327801
  0.64464393 0.24355625 0.29487435 0.99869784]
 [0.70732595 0.26441883 0.20384788 0.58420997 0.36365319 0.78757866
  0.95184626 0.99651206 0.66570073 0.87613294]
 [0.96467426 0.97705014 0.63600481 0.67580013 0.16473348 0.80502675
  0.10082007 0.17877406 0.97207974 0.36838522]
 [0.84219839 0.94665315 0.21886077 0.50881899 0.32909086 

In [55]:
random_matrix_B = np.random.rand(10,10)
print("Random 10x10 Matrix B:")
print(random_matrix_B)

Random 10x10 Matrix B:
[[0.55207673 0.82979829 0.63228269 0.27961153 0.161509   0.93869713
  0.07230449 0.61723333 0.71668191 0.44426187]
 [0.50231828 0.11130603 0.38208402 0.81199062 0.77329168 0.47243583
  0.45929298 0.19974896 0.66578106 0.99282559]
 [0.99183666 0.72116223 0.38229685 0.17778537 0.52742314 0.96919757
  0.76305973 0.77949859 0.23359263 0.21049779]
 [0.83019958 0.62143625 0.46275217 0.6434086  0.72469133 0.09458917
  0.62834548 0.59762253 0.3539877  0.38568059]
 [0.57397264 0.50656204 0.33094458 0.06949998 0.81989865 0.03532594
  0.20435319 0.81340129 0.79990785 0.59799997]
 [0.67268459 0.64777585 0.84206363 0.73634416 0.33505266 0.015329
  0.74835177 0.05123711 0.77941111 0.65433827]
 [0.81162093 0.32943614 0.54939784 0.37935549 0.37287101 0.72769505
  0.48755947 0.14258311 0.71691049 0.86640185]
 [0.35435676 0.98493021 0.93506839 0.35397201 0.1257106  0.35281606
  0.44210204 0.73205119 0.18670955 0.97625163]
 [0.65373268 0.51809221 0.47890904 0.00155026 0.14838817 0.

### Matrix Addition

In [57]:
addition_result = random_matrix_A + random_matrix_B
print("\nA + B: ")
print(addition_result)


A + B: 
[[1.53319292 0.86204831 1.54524913 1.25337941 1.09828271 1.85688246
  0.93329251 1.08495887 0.85133507 0.50742331]
 [0.88351836 0.37175832 0.47390302 1.05392483 1.46914103 0.82633776
  0.95692984 1.16088637 1.13589825 1.59183703]
 [1.08161493 0.90420098 1.12152139 1.0965755  0.52900063 1.09450577
  1.74676428 1.57123223 0.9562194  0.68305119]
 [1.330855   1.56134264 0.55051795 0.70349181 1.10235885 0.87794166
  1.274402   0.61349135 1.1528848  0.47357991]
 [0.8595333  0.73372173 0.36668036 0.86925481 1.15991143 0.12942207
  1.18507915 0.82125809 1.54911711 1.26624755]
 [0.76547584 1.63962293 0.93053297 1.50147089 0.99621839 0.22860702
  1.3929957  0.29479335 1.07428546 1.6530361 ]
 [1.51894688 0.59385497 0.75324571 0.96356545 0.73652421 1.51527372
  1.43940574 1.13909517 1.38261122 1.74253479]
 [1.31903102 1.96198036 1.5710732  1.02977214 0.29044409 1.15784281
  0.5429221  0.91082525 1.15878929 1.34463685]
 [1.49593107 1.46474536 0.69776981 0.51036924 0.47747903 0.58219311
  0

### Matrix Subtraction

In [59]:
subtraction_result = random_matrix_A - random_matrix_B
print("\nA - B: ")
print(subtraction_result)


A - B: 
[[ 0.42903946 -0.79754828  0.28068376  0.69415634  0.77526471 -0.0205118
   0.78868353 -0.14950779 -0.58202875 -0.38110043]
 [-0.1211182   0.14914625 -0.29026502 -0.5700564  -0.07744232 -0.11853391
   0.03834389  0.76138846 -0.19566387 -0.39381415]
 [-0.90205839 -0.53812348  0.35692768  0.74100476 -0.52584565 -0.84388938
   0.22064482  0.01223506  0.48903414  0.26205561]
 [-0.32954417  0.31847014 -0.37498639 -0.58332538 -0.3470238   0.68876331
   0.01771104 -0.58175371  0.4449094  -0.29778127]
 [-0.28841198 -0.27940235 -0.2952088   0.73025486 -0.47988587  0.05877019
   0.77637276 -0.80554448 -0.0506986   0.0702476 ]
 [-0.57989334  0.34407123 -0.7535943   0.02878256  0.32611307  0.19794901
  -0.10370783  0.19231914 -0.48453676  0.34435957]
 [-0.10429498 -0.06501731 -0.34554996  0.20485448 -0.00921782  0.05988361
   0.46428679  0.85392894 -0.05120976  0.00973108]
 [ 0.6103175  -0.00788007 -0.29906358  0.32182811  0.03902288  0.45221068
  -0.34128197 -0.55327714  0.78537019 -0.60

### Matrix Multiplication

In [61]:
multiplication_result = (random_matrix_A@random_matrix_B)
print("\nA * B:")
print(multiplication_result)


A * B:
[[4.4197628  4.0048607  3.54281202 2.36373407 2.85847332 2.83993642
  2.99630915 3.27613192 3.63803942 3.47653304]
 [2.70258761 2.87919241 2.91061269 1.71545311 1.66917372 1.73941519
  2.15335255 2.43700483 2.93227112 3.16905492]
 [3.57389709 3.06007031 2.95978815 1.94830805 1.9210589  2.48191806
  2.80682036 2.54599772 2.76112169 2.97519281]
 [2.7372018  2.01777708 2.34702982 1.86919782 1.84826326 1.94639373
  1.85183576 1.4429299  3.23458346 2.71098436]
 [2.94220321 2.16269494 2.30276002 1.68553495 1.73910522 1.79587635
  2.12621928 1.89004915 3.03363801 2.5066134 ]
 [3.23138449 2.44070517 2.77641597 2.51829345 2.50681473 1.73380352
  2.78305552 2.35368335 3.44853228 3.61618687]
 [4.06584598 4.01865677 4.18121398 2.71028756 2.16203488 2.70708991
  3.2955981  3.03038234 4.16725967 4.26615542]
 [3.86572951 3.34028229 3.26555143 2.55606186 2.41772095 2.8127314
  2.80657741 2.6509554  3.85305401 3.15952334]
 [3.13184633 3.13186269 3.25348566 2.51594918 2.12370126 2.47526801
  2.6

### Transpose of a Matrix

In [63]:
#Transpose of random_matrix_A
transpose_result_A= random_matrix_A.T
print("\nTranspose of Matrix A:")
print(transpose_result_A)

#Transpose of random_matrix_B
transpose_result_B= random_matrix_B.T
print("\nTranspose of Matrix B:")
print(transpose_result_B)


Transpose of Matrix A:
[[0.98111619 0.38120008 0.08977827 0.50065542 0.28556066 0.09279125
  0.70732595 0.96467426 0.84219839 0.97113012]
 [0.03225002 0.26045228 0.18303875 0.93990639 0.22715969 0.99184708
  0.26441883 0.97705014 0.94665315 0.6042988 ]
 [0.91296644 0.091819   0.73922453 0.08776578 0.03573578 0.08846934
  0.20384788 0.63600481 0.21886077 0.65061008]
 [0.97376788 0.24193422 0.91879013 0.06008322 0.79975483 0.76512672
  0.58420997 0.67580013 0.50881899 0.24716403]
 [0.93677371 0.69584936 0.00157749 0.37766752 0.34001278 0.66116573
  0.36365319 0.16473348 0.32909086 0.78301914]
 [0.91818533 0.35390193 0.12530819 0.78335248 0.09409613 0.21327801
  0.78757866 0.80502675 0.06213149 0.80254306]
 [0.86098802 0.49763686 0.98370455 0.64605652 0.98072596 0.64464393
  0.95184626 0.10082007 0.5016142  0.09572124]
 [0.46772554 0.96113741 0.79173365 0.01586882 0.00785681 0.24355625
  0.99651206 0.17877406 0.90880649 0.79551897]
 [0.13465316 0.47011719 0.72262677 0.7988971  0.74920926

### 1. Matrix is a two-dimensional array of numbers.

In [91]:
X = np.array([[1,2],[3,4],[5,6]])
print("3x2 Matrix:")
print(X)

3x2 Matrix:
[[1 2]
 [3 4]
 [5 6]]


### 2. Two matrices can be added if and only if they have the same dimensions.
### Two matrices can be multiplied if and only if the number of columns of the first matrix matches the number of rows of the second matrix.

In [67]:
A = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9]])
B = np.array([[5,4,3,2,1],[6,5,4,3,2],[7,6,5,4,3],[8,7,6,5,4],[9,8,7,6,5]])

add = A+B
times = A@B

print("Addition:",add)
print("Multiplication",times)

Addition: [[ 6  6  6  6  6]
 [ 8  8  8  8  8]
 [10 10 10 10 10]
 [12 12 12 12 12]
 [14 14 14 14 14]]
Multiplication [[115 100  85  70  55]
 [150 130 110  90  70]
 [185 160 135 110  85]
 [220 190 160 130 100]
 [255 220 185 150 115]]


### 3. Matrix transposition is interchanging a matrix rows into columns or columns into rows.
### Example: A 3x2 matrix will become a 2x3 matrix.

In [93]:
J = np.array([[1,2],[3,4],[5,6]])
print("Matrix J:\n",J)
transpose_J = J.T
print("Transpose of Matrix J:\n",transpose_J)

Matrix J:
 [[1 2]
 [3 4]
 [5 6]]
Transpose of Matrix J:
 [[1 3 5]
 [2 4 6]]


### 4. 

In [99]:
M = np.random.rand(5,5)
print("Random 5x5 matrix:\n",M)
sum_elements = (np.sum(M))
transpose_M = M.T
print("Sum of all Elements in the Matrix:\n",sum_elements)
print("Transpose of Matrix M:\n", transpose_M)

Random 5x5 matrix:
 [[0.2307699  0.78821223 0.39955148 0.61834188 0.33804441]
 [0.04363813 0.81265136 0.11031391 0.62453452 0.56536335]
 [0.65021091 0.91697091 0.21703638 0.75502347 0.14604562]
 [0.5512332  0.57032371 0.49091249 0.98500222 0.16613596]
 [0.45613809 0.8785757  0.82190409 0.18706266 0.10461385]]
Sum of all Elements in the Matrix:
 12.428610427433
Transpose of Matrix M:
 [[0.2307699  0.04363813 0.65021091 0.5512332  0.45613809]
 [0.78821223 0.81265136 0.91697091 0.57032371 0.8785757 ]
 [0.39955148 0.11031391 0.21703638 0.49091249 0.82190409]
 [0.61834188 0.62453452 0.75502347 0.98500222 0.18706266]
 [0.33804441 0.56536335 0.14604562 0.16613596 0.10461385]]


### 5. One possible application of each operation in computer science
### Matrix Addition: Blending Images
### Matrix Subtraction: Comparing Datasets
### Matrix Multiplication: Machine Learning


In [73]:
D = np.random.rand(10,10)
E = np.random.rand(10,10)

#a
addition = D + E
#b
subtraction = D - E
#c
multiplication = D@E

print(f"Addition: \n {addition} \n\n Subtraction:\n {subtraction} \n\nMultiplication:\n{multiplication}")


Addition: 
 [[1.15472313 0.518446   0.70683242 1.12601428 1.03870002 1.70147806
  1.45785862 1.1200332  1.16466808 1.16643502]
 [1.49218178 1.11962385 0.94758903 1.13696192 1.17856871 0.66061971
  0.92522996 0.24972729 0.39734603 1.20827586]
 [1.00753309 1.23948837 1.00417124 0.43987476 0.93133537 0.80345696
  0.45468628 0.72860842 1.31968009 1.24598863]
 [0.28100654 0.63350281 0.99829021 0.42152638 0.4948028  0.84443961
  0.90152315 1.22647883 0.84405212 1.70379426]
 [1.59287269 0.45417255 1.68281218 1.34347874 0.99388577 0.80507993
  0.35293904 1.00563234 1.51416299 0.79358762]
 [0.30871119 0.8299866  0.75216851 1.54430413 0.82404151 1.46202894
  1.24127102 1.59104327 1.49938796 1.20538257]
 [0.77095136 1.37121581 0.22957206 0.15620895 1.80495186 0.6683116
  0.26499279 0.86026269 0.92989771 1.41017358]
 [1.4828755  1.14436943 0.21487816 1.14097162 1.1909894  0.87867262
  1.66691032 0.9263731  0.47880375 0.92384305]
 [1.01033042 1.37512045 1.10681628 1.03088751 1.06218673 1.23626982
 